hydephp/framework

- src/MarkdownPageParser.php
We never really used the Front Matter in Markdown Pages so this PR removes them as it creates unnecessary complexity while not really gaining anything. We may of course re-add it in the future if/when we utilize it fully.
> 0.6.0 Remove support for Front Matter in Markdown Pages

- .gitignore
- phpdoc.dist.xml
- src/Actions/ConvertsArrayToFrontMatter.php
- src/Actions/ConvertsFooterMarkdown.php
- src/Actions/CreatesDefaultDirectories.php
- src/Actions/CreatesNewMarkdownPostFile.php
- src/Commands/BuildStaticSiteCommand.php
- src/Commands/Debug.php
- src/Commands/MakePostCommand.php
- src/Commands/MakeValidatorCommand.php
- src/Commands/PublishStubsCommand.php
- src/Commands/Validate.php
- src/HomeServiceProvider.php
Fixes #29 by adding missing class descriptions to all classes.
> Add internal PHPDoc class descriptions

- resources/views/components/docs/sidebar-footer.blade.php
- resources/views/components/docs/sidebar-header.blade.php
Fix bug where home buttons did not work properly on nested documentation levels.
> Use relative path helper for links

- resources/views/components/post/datePublished.blade.php
Updates the `hyde\framework\resources\views\components\post\datePublished.blade.php` component.
As always, if you have published the Blade components you will need to republish them to get the new changes.
> Fix #63, update component to show formatted dates

- .github/workflows/test-suite.yml
See https://github.com/hydephp/framework/issues/196
> Fix test matrix not fetching proper branch on PRs

- resources/data/filecache.json
- resources/views/components/article-excerpt.blade.php
- tests/Unit/BlogPostFrontMatterIsOptionalTest.php
> Handle undefined array key title in article-excerpt.blade.php 

- composer.json
- composer.lock
- src/Services/RssFeedService.php
- src/Services/SitemapService.php
Fixes https://github.com/hydephp/framework/issues/506
> Fix: #506: Move ext-simplexml in composer.json to suggest as it is not a strict dependency

- resources/views/components/article-excerpt.blade.php
- resources/views/components/post/article.blade.php
- resources/views/components/post/author.blade.php
- resources/views/components/post/image.blade.php
- resources/views/layouts/docs.blade.php
- src/Models/Image.php
- tests/Feature/Commands/StaticSiteBuilderPostModuleTest.php
- tests/Feature/ImageModelTest.php
- tests/Unit/Views/ArticleExcerptViewTest.php
Fixes https://github.com/hydephp/framework/issues/496
> Improve metadata for featured post images

- src/Foundation/HydeKernel.php
We're thrilled to announce HydePHP v1.0.0, the first general availability release of the Laravel-based static site generator you've been waiting for! HydePHP allows you to build lightning-fast static websites with ease, using the familiar syntax and functionality of the Laravel framework.
HydePHP is a powerful static site generator that is built on top of Laravel, one of the most popular PHP frameworks out there. HydePHP's architecture and design principles allow for a flexible and intuitive development experience, making it a great choice for developers looking to create static websites quickly and efficiently.
This release marks the first stable version of HydePHP, with many exciting new features and improvements. Here are some of the highlights:
- Upgraded to Laravel 10 and requires …
> HydePHP version v1.0.0

- .github/workflows/run-tests.yml
Missed this in https://github.com/hydephp/framework/pull/572
> Internal: Update test workflow to remove conditional as step should now always run

- README.md
- src/Foundation/HydeKernel.php
Updates readme and syncs up versioning
> HydePHP v1.3.2 - 2023-10-30

- resources/views/components/docs/documentation-article.blade.php
- tests/Feature/Services/HydeSmartDocsTest.php
Merges https://github.com/hydephp/develop/pull/1506
>  Improve the semantic documentation article Blade view 

- src/Foundation/HydeKernel.php
Framework version v1.4.3 https://github.com/hydephp/develop/commit/ad2364910bb431e8b0340af17754580efc19c4d5
> HydePHP v1.4.3 - 2024-02-07

- config/hyde.php
Merges pull request https://github.com/hydephp/develop/pull/1531 from hydephp/improve-media-asset-handling
> Add media extensions option to default config 

- src/Framework/Services/BuildService.php
Merges pull request https://github.com/hydephp/develop/1533
> Deprecate `BuildService::transferMediaAssets()` 

- src/Support/Includes.php
Merges pull request https://github.com/hydephp/develop/pull/1551
> Update includes facade to use trait instead of repeated logic

- src/Support/Includes.php
- tests/Feature/IncludesFacadeTest.php
Merges pull request https://github.com/hydephp/develop/pull/1552
> Add a new `Includes::html()` helper

- src/Framework/Actions/ConvertsMarkdownToPlainText.php
- tests/Feature/Actions/ConvertsMarkdownToPlainTextTest.php
Merges pull request https://github.com/hydephp/develop/pull/1561
> Update Markdown to plaintext formatter to trim whitespace

- tests/Feature/Actions/ConvertsMarkdownToPlainTextTest.php
Merges https://github.com/hydephp/develop/pull/1560
> Format and normalize files

- src/Foundation/HydeKernel.php
Please see the release notes in the development monorepo https://github.com/hydephp/develop/releases/tag/v1.5.0
> HydePHP v1.5.0 - 2024-02-13

- config/hyde.php
- resources/views/components/navigation/theme-toggle-button.blade.php
- resources/views/layouts/head.blade.php
- src/Console/Commands/DebugCommand.php
- src/Enums/Feature.php
- src/Facades/Features.php
- src/Foundation/HydeKernel.php
- src/Framework/Concerns/Internal/MockableFeatures.php
- src/Framework/Services/ValidationService.php
- src/Hyde.php
- tests/Feature/ConfigurableFeaturesTest.php
- tests/Feature/DarkmodeFeatureTest.php
- tests/Feature/HydeKernelTest.php
- tests/Unit/HydeHelperFacadeTest.php
Merges https://github.com/hydephp/develop/pull/1650 and https://github.com/hydephp/develop/pull/1652
> Introduce a new Feature enum to improve the Features facade

- src/Foundation/Concerns/ForwardsHyperlinks.php
- src/Foundation/Kernel/Hyperlinks.php
- src/Hyde.php
- tests/Feature/Foundation/HyperlinksTest.php
- tests/Feature/HydeKernelTest.php
Merges pull request https://github.com/hydephp/develop/pull/1591
> Add a `Hyde::route()` helper method

- src/helpers.php
- tests/Feature/HelpersTest.php
Merges pull request https://github.com/hydephp/develop/pull/1592
> Improved helper functions

- SECURITY.md
Merges pull request https://github.com/hydephp/develop/pull/1621
> Designate HydePHP v1.x as LTS 

- tests/Unit/TestingSupportHelpersMetaTest.php
Merges https://github.com/hydephp/develop/pull/1641
> Internal: Add a unit test

- src/Framework/Actions/PostBuildTasks/GenerateSitemap.php
- tests/Feature/Services/BuildTaskServiceTest.php
Merges pull request https://github.com/hydephp/develop/pull/1660
> Skip sitemap generation when there is no valid base URL

- resources/views/components/article-excerpt.blade.php
- resources/views/components/docs/search-widget.blade.php
- resources/views/components/post/article.blade.php
- resources/views/components/post/author.blade.php
- resources/views/components/post/image.blade.php
- resources/views/layouts/footer.blade.php
- resources/views/layouts/navigation.blade.php
- resources/views/pages/404.blade.php
- resources/views/pages/documentation-search.blade.php
- tests/Feature/SourceDirectoriesCanBeChangedTest.php
Merges pull request https://github.com/hydephp/develop/pull/1610
> Clean up HTML and Blade files

- src/Framework/Factories/BlogPostDataFactory.php
- tests/Unit/Pages/MarkdownPostHelpersTest.php
Merges pull request https://github.com/hydephp/develop/pull/1662
> Strip Markdown from automatic blog post descriptions

- src/Console/Commands/DebugCommand.php
- tests/Feature/Commands/DebugCommandTest.php
Merges pull request https://github.com/hydephp/develop/pull/1667
> Update debug command to print binary path when running in the Phar standalone

- src/Foundation/HydeKernel.php
Please see the release notes in the development monorepo https://github.com/hydephp/develop/releases/tag/v1.6.0
> HydePHP v1.6.0 - 2024-04-17

- src/Console/Commands/BuildSitemapCommand.php
Merges pull request https://github.com/hydephp/develop/pull/1677
> Fix command description wording

- src/Markdown/Processing/CodeblockFilepathProcessor.php
- tests/Feature/Services/Markdown/CodeblockFilepathProcessorTest.php
Merges pull request https://github.com/hydephp/develop/pull/1693
> Add custom filepath label support for HTML comments

- src/Console/Commands/ServeCommand.php
- tests/Unit/ServeCommandOptionsUnitTest.php
Merges pull request https://github.com/hydephp/develop/pull/1694
> Update realtime compiler open flag to support specifying the page to open

- config/hyde.php
- resources/views/components/navigation/theme-toggle-button.blade.php
- src/Facades/Features.php
- tests/Feature/ConfigurableFeaturesTest.php
- tests/Feature/DarkmodeFeatureTest.php
Merges pull request https://github.com/hydephp/develop/pull/1697
> Add a config option to disable theme toggle buttons to automatically use browser settings

- src/Foundation/Kernel/Filesystem.php
Merges pull request https://github.com/hydephp/develop/pull/1699
> Refactor filesystem helpers

- .gitattributes
Merges pull request https://github.com/hydephp/develop/pull/1702
> Fix gitattributes normalization across all packages

- src/Framework/Features/Navigation/NavigationMenu.php
- tests/Feature/NavigationMenuTest.php
- tests/Unit/NavigationDataFactoryUnitTest.php
Merges pull request https://github.com/hydephp/develop/pull/1703
> Honour front matter navigation groups set in front matter regardless of subdirectory setting

- src/Support/DataCollections.php
Merges pull request https://github.com/hydephp/develop/pull/1717
> Use late static bindings to support overriding data collections file finding

- .github/workflows/run-tests.yml
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
> Internal: Enable merge queue

- src/Console/Commands/RouteListCommand.php
- tests/Feature/Commands/RouteListCommandTest.php
Merges pull request https://github.com/hydephp/develop/pull/1724
> Add a JSON output format option to the route list command

- src/Foundation/Kernel/Hyperlinks.php
- tests/Feature/Foundation/HyperlinksTest.php
- Merges pull request https://github.com/hydephp/develop/pull/1727
- Merges pull request https://github.com/hydephp/develop/pull/1725
> Code cleanup and refactors

- composer.json
- tests/Feature/MarkdownFileParserTest.php
Merges pull request https://github.com/hydephp/develop/pull/1728
> Fix undefined array key exception for empty Markdown pages

- src/Foundation/Kernel/Hyperlinks.php
- src/Framework/Actions/PostBuildTasks/GenerateSitemap.php
- tests/Feature/Foundation/HyperlinksTest.php
- tests/Feature/HelpersTest.php
- tests/Feature/SitesWithoutBaseUrlAreHandledGracefullyTest.php
- tests/Feature/Views/MetadataViewTest.php
- tests/Unit/Foundation/HyperlinksUrlPathHelpersTest.php
Merges pull request https://github.com/hydephp/develop/pull/1726
> Improve behaviour when a site URL is not explicitly set

- src/Support/DataCollections.php
- tests/Feature/DataCollectionTest.php
Merges pull request https://github.com/hydephp/develop/pull/1733
> DataCollections improvements

- src/Console/Commands/RebuildPageCommand.php
- src/Foundation/Kernel/Filesystem.php
- src/Framework/Actions/CreatesNewPageSourceFile.php
- src/Framework/Concerns/RegistersFileLocations.php
- src/Framework/Factories/FeaturedImageFactory.php
- src/Framework/Services/ViewDiffService.php
- src/Pages/Concerns/HydePage.php
- src/Pages/DocumentationPage.php
- src/Support/DataCollections.php
- src/Support/Models/RouteKey.php
- src/helpers.php
- tests/Feature/HelpersTest.php
Merges pull request https://github.com/hydephp/develop/pull/1753
> Deprecate the global `unslash` function

- src/Console/Commands/DebugCommand.php
- tests/Feature/Commands/DebugCommandTest.php
Merges pull request https://github.com/hydephp/develop/pull/1756
> Remove the Git version displays

- src/Foundation/Kernel/Hyperlinks.php
- src/Framework/Exceptions/BaseUrlNotSetException.php
Merges pull request https://github.com/hydephp/develop/pull/1759
> Deprecate the `BaseUrlNotSetException` class

- src/Framework/Factories/Concerns/PageDataFactory.php
- tests/Feature/Commands/BuildSitemapCommandTest.php
Merges pull request https://github.com/hydephp/develop/pull/1761
> Internal: Update tests to cover missing code coverage lines

- src/Console/Commands/RouteListCommand.php
Merges pull request https://github.com/hydephp/develop/pull/1725
> Clean up and refactor route list command code

- .github/workflows/run-tests.yml
- tests/Feature/Services/Markdown/CodeblockFilepathProcessorTest.php
Merges pull request https://github.com/hydephp/develop/pull/1769
> Fix source code formatting

- src/Framework/Features/XmlGenerators/SitemapGenerator.php
Merges pull request https://github.com/hydephp/develop/pull/1767
> Add a version prefix to the sitemap generator version attribute

- src/Foundation/Internal/LoadYamlConfiguration.php
- tests/Feature/LoadYamlConfigurationTest.php
Merges pull request https://github.com/hydephp/develop/pull/1770
> Improve the Yaml configuration loader

- src/Foundation/ConsoleKernel.php
- tests/Feature/ConsoleKernelTest.php
Merges pull request https://github.com/hydephp/develop/pull/1772
> Refactor console kernel bootstrapper loading

- tests/Feature/Commands/MakePostCommandTest.php
- tests/Feature/PostsAuthorIntegrationTest.php
- tests/Feature/StaticSiteBuilderDocumentationModuleTest.php
- tests/Feature/StaticSiteBuilderPostModuleTest.php
- tests/Unit/GetLatestMarkdownPostsTest.php
Merges pull request https://github.com/hydephp/develop/pull/1777
> Internal: Clean up and refactor test code

- src/Foundation/HydeKernel.php
Framework version v1.7.1 https://github.com/hydephp/develop/commit/056d98f0d16687dbf600a0270c54662c567f60e8
> HydePHP v1.7.1 - 2024-07-05

- tests/Unit/Views/ArticleExcerptViewTest.php
Merges pull request https://github.com/hydephp/develop/pull/1789
> Internal: Clean up test code

- src/Foundation/HydeKernel.php
Framework version v1.7.2 https://github.com/hydephp/develop/commit/ac3cac87b43055a0ab7ad64830b4d5dd73f378f2
> HydePHP v1.7.2 - 2024-07-08

- resources/views/components/docs/mobile-navigation.blade.php
- resources/views/components/docs/search-widget.blade.php
- resources/views/layouts/docs.blade.php
Merges pull request https://github.com/hydephp/develop/pull/2005
> Improved printed documentation views 

- src/Console/Commands/ServeCommand.php
- tests/Feature/Commands/ServeCommandTest.php
Merges pull request https://github.com/hydephp/develop/pull/2017
> Shorten the realtime compiler server start message

- tests/Feature/Services/Markdown/ShortcodeProcessorTest.php
- tests/Feature/Services/RssFeedServiceTest.php
- tests/Feature/Support/ProjectFileTest.php
- tests/Unit/Foundation/HyperlinkFileHelperRelativeLinkTest.php
- tests/Unit/Foundation/HyperlinkFormatHtmlPathTest.php
- tests/Unit/Pages/HtmlPageTest.php
- tests/Unit/Pages/MarkdownPageTest.php
- tests/Unit/Pages/MarkdownPostParserTest.php
- tests/Unit/PostAuthorTest.php
- tests/Unit/Views/LinkComponentViewTest.php
Merges pull request https://github.com/hydephp/develop/pull/1796
> Internal: Improve test static analysis and improve tests 

- tests/Feature/BladeMatterParserTest.php
- tests/Feature/NavigationDataTest.php
- tests/Feature/TypedConfigFacadeTest.php
- tests/Feature/YamlConfigurationFeatureTest.php
- tests/Unit/ServeCommandOptionsUnitTest.php
- tests/Unit/TestingSupportHelpersMetaTest.php
Merges pull request https://github.com/hydephp/develop/pull/1808
> Internal: Improve testing helpers

- src/Console/Commands/ServeCommand.php
- tests/Unit/ServeCommandOptionsUnitTest.php
Merges pull request https://github.com/hydephp/develop/pull/1867
> Refactor the serve command and add more unit tests for it

- src/Foundation/Concerns/BaseFoundationCollection.php
- src/Foundation/Concerns/HandlesFoundationCollections.php
- src/Foundation/Facades/Files.php
- src/Foundation/Facades/Pages.php
- src/Foundation/Facades/Routes.php
- src/Foundation/Internal/LoadYamlConfiguration.php
- src/Foundation/Kernel/FileCollection.php
- src/Foundation/Kernel/PageCollection.php
- src/Foundation/Kernel/RouteCollection.php
- src/Framework/Features/Metadata/MetadataBag.php
Merges pull request https://github.com/hydephp/develop/pull/1868
> Refactor code to increase code quality and type coverage

- config/commands.php
Merges pull request https://github.com/hydephp/develop/pull/1879
> Hide the Torchlight install command

- resources/views/pages/404.blade.php
Merges pull request https://github.com/hydephp/develop/pull/1880
> Update 404 page home link fallback to lead to the domain root

- config/commands.php
- tests/Feature/Commands/CacheClearCommandTest.php
Merges pull request https://github.com/hydephp/develop/pull/1881
> Register the cache clear command

- src/Foundation/Kernel/Hyperlinks.php
- src/Framework/Factories/FeaturedImageFactory.php
- src/Framework/Features/Blogging/Models/FeaturedImage.php
- src/Framework/Features/Metadata/PageMetadataBag.php
- tests/Feature/Foundation/HyperlinksTest.php
Merges pull request https://github.com/hydephp/develop/pull/1882
> Normalize protocol relative URL handling

- src/Pages/Concerns/HydePage.php
- tests/Unit/Pages/BladePageUnitTest.php
- tests/Unit/Pages/DocumentationPageUnitTest.php
- tests/Unit/Pages/HtmlPageUnitTest.php
- tests/Unit/Pages/InMemoryPageUnitTest.php
- tests/Unit/Pages/MarkdownPageUnitTest.php
- tests/Unit/Pages/MarkdownPostUnitTest.php
Merges pull request https://github.com/hydephp/develop/pull/1885
> Cleanup the canonical URL helper method

- src/Framework/Features/Metadata/PageMetadataBag.php
- src/Markdown/Contracts/FrontMatter/PageSchema.php
- tests/Feature/MetadataTest.php
- tests/Feature/Views/MetadataViewTest.php
- tests/Unit/SchemaContractsTest.php
Merges pull request https://github.com/hydephp/develop/pull/1884
> Support setting page descriptions in front matter for all page types

- src/Framework/Features/Metadata/PageMetadataBag.php
- tests/Feature/MetadataTest.php
Merges pull request https://github.com/hydephp/develop/pull/1886
> Clean up and refactor code

- resources/views/components/article-excerpt.blade.php
Merges pull request https://github.com/hydephp/develop/pull/1889
> Fix URL metadata for blog posts not using customized post output directories

- src/Foundation/HydeKernel.php
- tests/Feature/HydeKernelTest.php
Merges pull request https://github.com/hydephp/develop/pulls/1786
> Update the `HydeKernel` array representation to include the Hyde version 

- src/Foundation/Concerns/ImplementsStringHelpers.php
- src/Framework/Actions/CreatesNewMarkdownPostFile.php
- src/Framework/Actions/CreatesNewPageSourceFile.php
- src/Framework/Features/Navigation/DocumentationSidebar.php
- src/Framework/Features/Navigation/NavItem.php
- tests/Feature/HydeKernelTest.php
- tests/Feature/InternationalizationTest.php
- tests/Unit/HydeHelperFacadeMakeSlugTest.php
Merges pull request https://github.com/hydephp/develop/pull/2070
> Automatically transliterate logographic inputs for slug generation

- src/Console/Commands/ServeCommand.php
- src/Foundation/HydeKernel.php
- tests/Feature/Commands/ServeCommandTest.php
Fixes https://github.com/hydephp/hyde/issues/276
> Fix serve command not handling project path with spaces

- src/Foundation/HydeKernel.php
Framework version v2.0.1 https://github.com/hydephp/develop/commit/ccecf88e63905b7f6e52146865dd8e151b7f0364
> HydePHP v2.0.1 - 2025-10-04
