- src/Commands/BuildStaticSiteCommand.php
This PR adds a few new options to the build command:
New options:
- --run-dev       Run the NPM run dev script after build to automatically build frontend assets
- --run-prod     Run the NPM run prod script after build to automatically build frontend assets
- --clean           Empties the output directory before building. Perfect to clean up old files.
- --force           Allows file deletions without prompting user for confirmation
It also has a UX improvement where the progress bar is not shown for empty collections. It also adds a splash of color to the progress bar titles.
> Add new options to the build command to improve the user experience 

- resources/views/pages/index.blade.php
- src/Hyde.php
New facade method:
Hyde::getLatestPosts() which serves as a static shorthand for \Hyde\Framework\Models\MarkdownPost::getCollection()
> Add the Hyde::getLatestPosts() shorthand to get the latest posts collection

- config/commands.php
- src/HydeServiceProvider.php
Previously, the Hyde commands were loaded in the config which requires the config to be republished whenever new commands are added to keep them in sync.
This PR moves the commands into the Hyde Service Provider instead.
> Load commands in service provider instead of config/commands.php

- config/hyde.php
- resources/views/components/docs/sidebar-header.blade.php
- src/Actions/GeneratesNavigationMenu.php
- src/Hyde.php
- src/StaticPageBuilder.php
The output directory for the documentation pages can now be changed. The compiled links will automatically be updated too.
For example, this can be used to specify the version being generated. I plan on using this for the https://github.com/hydephp/docs repo.
> Improve Docgen Feature by allowing the output directory to be dynamically changed

- config/view.php
- src/Hyde.php
Please make sure to republish the config/view.php file
> Remove deprecated methods

- resources/views/components/docs/sidebar-header.blade.php
- src/Hyde.php
Original bug: #21 Documentation sidebar header should link to readme if that exists but an index does not
> Fix #21 by dynamically routing to the docs index

- composer.json
- composer.lock
I've been debating whether to include Torchlight as a suggestion or a dependency, and settled on the former. While Torchlight is an extension and not a core dependant, I think most users of Hyde are interested in tech and will probably want to use code examples. Installing Torchlight explicitly allows the integration to be tested better, and create a more predictable environment.
> Require Torchlight

- config/commands.php
- src/Commands/HydeBasePublishingCommand.php
- src/Commands/HydeBuildStaticSiteCommand.php
- src/Commands/HydeDebugCommand.php
- src/Commands/HydeMakePostCommand.php
- src/Commands/HydeMakeValidatorCommand.php
- src/Commands/HydePublishConfigsCommand.php
- src/Commands/HydePublishHomepageCommand.php
- src/Commands/HydePublishStubsCommand.php
- src/Commands/HydePublishViewsCommand.php
- src/Commands/HydeValidateCommand.php
- src/HydeServiceProvider.php
This PR refactors all the commands to follow the format of Hyde + CommandDescriptor + Command
<s>BasePublishingCommand</s> => HydeBasePublishingCommand
<s>BuildStaticSiteCommand</s> => HydeBuildStaticSiteCommand
<s>Debug</s> => HydeDebugCommand
<s>HydePublishConfigsCommand</s> => HydePublishConfigsCommand
<s>HydePublishHomepageCommand</s> => HydePublishHomepageCommand
<s>HydePublishViewsCommand</s> => HydePublishViewsCommand
<s>MakePostCommand</s> => HydeMakePostCommand
<s>MakeValidatorCommand</s> => HydeMakeValidatorCommand
<s>PublishStubsCommand</s> => HydePublishStubsCommand
<s>Validate</s> => HydeValidateCommand
> #32 refactor command class names to be consistent

- resources/views/layouts/app.blade.php
- resources/views/layouts/docs.blade.php
- resources/views/layouts/navigation.blade.php
Part of https://github.com/hydephp/hyde/issues/50 and https://github.com/hydephp/framework/issues/34
> Move scripts into app.js

- src/Commands/HydeRebuildStaticSiteCommand.php
- src/HydeServiceProvider.php
- src/Services/BuildService.php
- src/StaticPageBuilder.php
Using the `php hyde build` command is great and all that, but when you just need to update that one file it gets a little... overkill.
Let's solve that! Use the `php hyde rebuild <file>` command!
In the future it will support an array of files, but for now, the rebuild command will recompile just that file.
The command acts like an alias to a new service class, the Build Service, which accepts a single source path.
We can in the future make a wrapper for the service that allows for an array input which then starts a build loop of build service classes.
Once the service class is instantiated we call the execute action method to start the build loop. If here the service determines which model to render based on the file path prefix. If a file is not found or a model does not exist an error …
> #38 Add a rebuild command to the Hyde CLI to rebuild a specific file

- resources/views/pages/404.blade.php
Fix the bug where the 404 page "go home" button did not work on nested pages by first attempting to link to the app url if it is set, otherwise directly to the root path (href="/").
> Fix the 404 route bug

- resources/views/components/docs/sidebar-header.blade.php
The documentation heading link in the last patch did not work as expected, this PR should fix that.
> Fix the documentation page header link

- src/StaticPageBuilder.php
Fixed by allowing recursion in the `mkdir` function call. The commit is backwards compatible.
> Fix bug #47 StaticPageBuilder not able to create nested documentation directories

- resources/views/layouts/app.blade.php
Checks if a `favicon.ico` file exists in the `_media` directory, and if so, injects a link with using the Hyde relative path helper.
> Add a favicon link automatically if the file exists

- src/Actions/CreatesNewPageSourceFile.php
- src/Actions/CreatesNewStaticPageSourceFile.php
- src/Commands/HydeMakePageCommand.php
- src/HydeServiceProvider.php
We have a neat command to create blog posts. We should have one for pages as well. We can use a flag option to select if it should be a Markdown or a Blade pages.
With Markdown the selected title will be added as a front matter, with Blade the default layout will be used as a stub, and the PHP title injected.
> Create new command to scaffold pages

- resources/views/components/navigation/navigation-link.blade.php
- resources/views/layouts/navigation.blade.php
This PR rewrites the main navigation menu in accordance with #59 to keep a single source of truth for the navigation menu.
Before this PR there were two separate DOM elements for the main navigation menu. This PR merges them into one single HTML element which makes it much easier to maintain as we no longer need to keep the menus synced.
See https://github.com/hydephp/hyde/pull/58 for the necessary frontend styles and script updates.
> Rewrite main navigation menu

- src/Commands/HydeRebuildStaticSiteCommand.php
Part one in my refactor of the build service process
> Supply `_media` as the path argument in the `hyde:rebuild` command to copy all media files.

- resources/views/layouts/docs.blade.php
Fixes #76 where the root cause was that the sidebar-backdrop causes issues if Tailwind is not loaded.
Upgrade guide:
If you have previously published the resources\views\layouts\docs.blade.php file you will need to republish it to get the patch.
> Add base styles to documentation layout

- config/view.php
- src/Actions/CreatesDefaultDirectories.php
- src/Actions/CreatesNewPageSourceFile.php
- src/Actions/GeneratesNavigationMenu.php
- src/Actions/PublishesHomepageView.php
- src/Commands/HydePublishHomepageCommand.php
- src/Commands/HydePublishTestFilesCommand.php
- src/Commands/HydeRebuildStaticSiteCommand.php
- src/HydeServiceProvider.php
- src/Models/BladePage.php
- src/Services/BuildService.php
- src/Services/CollectionService.php
- src/StaticPageBuilder.php
Changes: Blade pages are now stored in the `_pages` directory, same as Markdown pages.
The config/view.php is updated to include the new source directory. Run php hyde publish:configs --force to update.
> Change blade source directory to _pages

- src/Commands/HydeBasePublishingCommand.php
Deprecated as it adds unnecessary complexity.
Call usages can be refactored similarly to the method used here, where the command serves as a wrapper for the action.
Hyde\Framework\Actions\PublishesDefaultFrontendResourceFiles 
Hyde\Framework\Commands\HydePublishFrontendResourcesCommand
> Deprecate internal abstract class HydeBasePublishingCommand

- src/DocumentationPageParser.php
- src/MarkdownPageParser.php
- src/MarkdownPostParser.php
As a side effect, documentation pages now have support for setting the page title using front matter. However, using front matter in documentation pages, and regular pages, is still completely optional.
> Strip front matter from documentation pages

- resources/views/components/post/article.blade.php
- resources/views/components/post/author.blade.php
- resources/views/components/post/category.blade.php
- resources/views/layouts/post.blade.php
- src/Models/HasAuthor.php
- src/Models/HasMetadata.php
- src/Models/MarkdownPost.php
Before, the only option to add further data to authors for blog posts, for instance a website link, was through the authors.yml config file. You can now set the author data on a per-post basis.
Usage:
```markdown
---
title: Custom Author...
author: 
username: mr_hyde
name: Miss Hyde
website: https://github.com/hydephp
```
Note that custom authors take precedence and will not merge any existing data. For example, if you have a user defined in config that has a website link and display name, and you use the new way to add an author in front matter and only set the display name, the website will be null.
> Allow author array data to be added in front matter

- config/markdown.php
- src/Actions/ServiceActions/HasConfigurableMarkdownFeatures.php
- src/Actions/ServiceActions/HasMarkdownFeatures.php
- src/Actions/ServiceActions/HasTorchlightIntegration.php
- src/Markdown.php
- src/Services/MarkdownConverterService.php
Adds a new config that can be used to manage the default CommonMark extensions and add your own. You can also add and override the environment configuration.
Improves the main Markdown Service class by extracting parts into Service-Action Traits, and adding a more programmatic approach where settings can be changed at runtime using method chaining.
> Overhaul the Markdown Converter Service to make it easier to customize and extend

- resources/views/layouts/app.blade.php
Makes so that the Hyde stylesheet is loaded before the Tailwind app.css. This makes it easier to customize Hyde styles by overriding them in resources/assets/app.css, which is compiled into _site/media/app.css which is now loaded after Hyde.css.
> Change priority of stylesheets

- config/hyde.php
- resources/assets/README.md
- resources/assets/package.json
- resources/views/layouts/app.blade.php
- resources/views/layouts/scripts.blade.php
- resources/views/layouts/styles.blade.php
- src/Concerns/Internal/AssetManager.php
- src/Concerns/Internal/FileHelpers.php
- src/Contracts/AssetServiceContract.php
- src/Services/AssetService.php
- tests/Feature/AssetServiceTest.php
Refactors the internal Asset Service, to better add support for Laravel Mix https://github.com/hydephp/hyde/issues/124, as well as removing support for the Tailwind CDN https://github.com/hydephp/hydefront/issues/25
> Refactor assets managing, allowing for Laravel Mix, removing CDN support for Tailwind

- config/hyde.php
- resources/views/components/docs/sidebar-header.blade.php
Fixes #233 by implementing the following config section:
```php
/*
|--------------------------------------------------------------------------
| Documentation Sidebar Header Name
|--------------------------------------------------------------------------
|
| By default, the sidebar title shown in the documentation page layouts uses
| the app name suffixed with "docs". You can change it with this setting.
|
*/
'docsSidebarHeaderTitle' => config('app.name') . ' Docs',
```
> Allow documentation sidebar header name to be changed

- .gitattributes
File is "borrowed" from Laravel/Framework, https://github.com/laravel/framework/blob/9.x/.gitattributes
> Create .gitattributes, fixes #223

- src/Commands/HydeBuildStaticSiteCommand.php
- tests/Feature/Commands/BuildStaticSiteCommandTest.php
It also removes the --clean and --force flag as they are no longer needed.
> Always empty the _site directory when running the static site build command

- src/Services/AssetService.php
Needed since the internal JS structure has been refactored to use event listeners instead of onclick HTML attributes
> Update HydeFront version to v1.5.x

- resources/views/components/docs/navigation.blade.php
- resources/views/components/navigation/theme-toggle-button.blade.php
- resources/views/layouts/app.blade.php
- resources/views/layouts/docs.blade.php
- resources/views/layouts/head.blade.php
- resources/views/layouts/scripts.blade.php
The frontend for the Hyde documentation module was originally based on Laradocgen, this branch migrates to its successor, Lagrafo. I may keep around the original ("classic") layout for a while; though the Lagrafo port has much better usability.
Fixing both https://github.com/hydephp/framework/issues/236 and https://github.com/hydephp/framework/issues/290.
> Refactor docs layout to use Lagrafo instead of Laradocgen

- src/Models/DocumentationSidebarItem.php
- src/Services/DocumentationSidebarService.php
- tests/Feature/Services/DocumentationSidebarServiceTest.php
Adding the following to a documentation page will prevent it from showing up in the sidebar, it will however still be compiled.
```markdown
---
hidden: true
---
```
> Fix #310, allow documentation pages to be hidden from sidebar using front matter

- resources/views/layouts/docs.blade.php
Since the main background is loaded in components later in the DOM we need a fallback style for the body element to make sure there is no flicker of white light which can be problematic for people with photosensitive issues
See https://github.com/hydephp/framework/issues/314
> Fix #314, add background color fallback to documentation page body

- resources/views/components/article-excerpt.blade.php
- tests/Unit/Views/ArticleExcerptViewTest.php
The component was pretty outdated and was referencing front matter directly. This this PR refactors the component to use the Author and DateString models.
Fixes #306 bug in article excerpt where author name uses front matter directly causing exception
> Refactor post excerpt component to be less reliant on directly using front matter and add view test

- src/Commands/HydeBuildStaticSiteCommand.php
- src/Commands/HydeRebuildStaticSiteCommand.php
- src/Concerns/Internal/BuildActionRunner.php
- src/Services/DiscoveryService.php
- src/Services/RebuildService.php
- tests/Feature/BuildServiceTest.php
- tests/Feature/DiscoveryServiceTest.php
- tests/Feature/SourceDirectoriesCanBeChangedTest.php
- tests/Unit/BuildServiceCanFindModelFromCustomSourceFilePathTest.php
- tests/Unit/DiscoveryServiceCanFindModelFromCustomSourceFilePathTest.php
- tests/Unit/SourceFilesInCustomDirectoriesCanBeCompiledTest.php
Since the BuildService mainly contains helpers regarding file discovery, this PR renames it to DiscoveryService. And since I think it satisfies all requirements in the related issue, I think this will close https://github.com/hydephp/framework/issues/336.
> Change BuildService to DiscoveryService

- src/Models/DocumentationSidebarItem.php
- tests/Feature/Services/DocumentationSidebarServiceTest.php
Makes so that the default priority value for documentation sidebar pages is 500. When an item is present in config, they get priority 250 + their order in the array, thus still putting them before pages without a defined priority, while allowing front matter to override and be put before config orderings.
> Add sidebar config offset, fix #307

- resources/views/components/article-excerpt.blade.php
- resources/views/components/docs/labeled-sidebar-navigation-menu.blade.php
- resources/views/components/docs/sidebar-navigation-menu.blade.php
- resources/views/homepages/welcome.blade.php
- resources/views/layouts/docs.blade.php
- resources/views/layouts/head.blade.php
- resources/views/layouts/navigation.blade.php
- src/Actions/GeneratesNavigationMenu.php
- src/Commands/HydeBuildStaticSiteCommand.php
- src/Concerns/Internal/FileHelpers.php
- tests/Unit/FileHelperPageLinkPrettyUrlTest.php
- tests/Unit/FileHelperRelativeLinkTest.php
- tests/Unit/HydeFileHelperForPageLinksCanCreatePrettyUrlsTest.php
- tests/Unit/TestBuildStaticSiteCommandFlagToEnablePrettyUrls.php
By setting `prettyUrls'` to `true` in the Hyde config, Hyde will now render links without the `.html` file extension.
This is done by using a new pageLink helper. The existing relativeLink used by Hyde includes the new helper by default.
When creating custom Blade pages you can use any of the link helpers to create links where the .html extension is removed depending on the config setting.
Since "pretty URLs" break links when viewing locally, you can keep the setting to the default false, but instead add the `--pretty-urls` option to the `php hyde build` command when you are ready to build for deployment.
```blade
<a href="{{ Hyde::relativeLink('index.html', $currentPage) }}">Back to home page</a>
<a href="{{ Hyde::pageLink('index.html') }}">Back to home page</a>
```
Live preview at …
> Add configurable "pretty URLs"

- src/Commands/HydeBuildStaticSiteCommand.php
- src/Concerns/Internal/AssetManager.php
- src/HydeServiceProvider.php
Resolves a todo related to https://github.com/hydephp/framework/pull/333 and swaps out the getter used to fetch the AssetService to retrieve it from the new Singleton in the service container loaded by the HydeServiceProvider.
> Load asset service from the service container

- resources/views/components/navigation/navigation-brand.blade.php
- resources/views/layouts/navigation.blade.php
Fix #379: Extract navigation menu logo to component to make it easier to customize
You can now customize the following component in `@include('hyde::components.navigation.navigation-brand')` 
```blade
<a aria-label="Home page link" href="{{ $homeRoute }}" class="font-bold px-4">
{{ config('hyde.name', 'HydePHP') }}
</a>
```
> Fix #379: Extract menu logo to component

- composer.json
- config/hyde.php
- src/Commands/HydeBuildStaticSiteCommand.php
- src/Services/SitemapService.php
- tests/Feature/Commands/BuildStaticSiteCommandTest.php
- tests/Feature/Services/SitemapServiceTest/SitemapServiceTest.php
When a site_url is set, (and the feature is not disabled in the config), a sitemap.xml will automatically be generated during the static site building process.
- Adds sitemap.xml generation
- `ext-simplexml` has been added as a requirement to `composer.json`
- The order of page builders have been changed, so that Blade and Markdown pages are compiled first.
This allows you to browse the most common parts of the site (like the index page) while the other
pages are being generated.
- Merge "Site URL Configuration" options. Please republish your configs.
> Add sitemap.xml generation

- config/hyde.php
Removes the annotation and rewrites the inline documentation. There are no functional or behavioral changes affected by this.
> Fix #403: Remove @HydeConfigVersion annotation from config/hyde.php

- config/hyde.php
- src/Commands/HydeBuildStaticSiteCommand.php
- src/Models/Author.php
- src/Models/MarkdownPost.php
- src/Services/RssFeedService.php
- tests/Feature/Commands/BuildStaticSiteCommandTest.php
- tests/Feature/Services/RssFeedServiceTest.php
- tests/Feature/Services/SitemapServiceTest.php
- tests/Feature/Services/SitemapServiceTest/RssFeedServiceTest.php
When enabled, an RSS feed with your Markdown blog posts will be generated when you compile your static site.
Note that this requires that a site_url is set!
```php // config/hyde.php
'generateRssFeed' => true, // Default is true
```
You can customize the output filename using the following:
```php // config/hyde.php
'rssFilename' => 'feed.xml', // Default is feed.rss
```
You can set the RSS channel description using the following:
```php // config/hyde.php
'rssDescription' => 'A collection of articles and tutorials from my blog', // Example
```
If an rssDescription is not set one is created by appending "RSS Feed" to your site name.
> Add RSS feed for Markdown blog posts

- src/Services/SitemapService.php
Priorities are set as follows:
```
index.html: 1
404.html: 0.5
Markdown and Blade pages: 0.9
Documentation pages: 0.9
Blog posts: 0.75
```
> Fix #429: Add page priorities to sitemap generation

- src/Actions/GeneratesDocumentationSearchIndexFile.php
- src/Commands/HydeBuildRssFeedCommand.php
- src/Commands/HydeBuildSearchCommand.php
- src/Commands/HydeBuildSitemapCommand.php
- src/HydeServiceProvider.php
- tests/Feature/Actions/GeneratesDocumentationSearchIndexFileTest.php
- tests/Feature/Commands/HydeBuildSearchCommandTest.php
Adds an action which generates a search index for documentation pages used for the [HydeSearch plugin](https://github.com/caendesilva/HydeSearch)
The way it currently works is that it takes a plain-text representation of all Markdown documentation pages and adds them paired with metadata such as the page title and URI path.
It is pretty slow to generate, so I have not yet added it to the `hyde build` command. Instead, it's generated using `php hyde build:search`.
The reason it's slow, is that each Markdown page needs to be parsed into a Page model, then the Markdown body is compiled to HTML as I found that to be the easiest way to convert it to plain text (using regex).
> These are not at all proper benchmarks, but an approximate of how long it took on my machine.
Generating a search …
> Create the backend search index generation for documentation pages

- .github/dev-docs/documentation-pages.md
- config/hyde.php
- resources/views/layouts/docs.blade.php
- src/Commands/HydeBuildSearchCommand.php
- src/Commands/HydeBuildStaticSiteCommand.php
- src/Helpers/Features.php
Make the search feature configurable and toggleable.
Also adds documentation to the dev-docs.
Also automatically generates the search index when running `hyde build`.
Some code refactoring and cleanup. Bugfixes. UX/UI niceties.
> Make the search feature configurable and toggleable

- composer.json
- composer.lock
- src/Commands/HydeServeCommand.php
- src/StaticPageBuilder.php
- tests/Feature/Commands/HydeServeCommandTest.php
Companion release to the rewrite in [hydephp/realtime-compiler](https://github.com/hydephp/realtime-compiler)
> Rewrite Realtime Compiler

- src/Commands/HydeBuildStaticSiteCommand.php
- tests/Feature/Commands/BuildStaticSiteCommandTest.php
Fixes https://github.com/hydephp/framework/issues/482 and https://github.com/hydephp/framework/issues/482#issuecomment-1146645266
Now checks if there are blog posts before creating the RSS feed, and if there are documentation pages before generating the search page and JSON index.
Note that this only changes behaviour for the `php hyde build` command. You can still generate the files by calling `build:rss` and `build:search`.
> Skip generating auxiliary files in the main built loop when there is no underlying content

- composer.json
- composer.lock
Since it is a dev-dependency, but for developing hyde/hyde projects it belongs there
> Move back hyde/realtime-compiler to hyde/hyde

- src/Application.php
- src/Commands/HydePackageDiscoverCommand.php
- src/HydeServiceProvider.php
Creates a Laravel Application to enable auto discovery of packages and service providers.
Also adds a command to create the cache of discovered packages. `php hyde packages:discover`.
> v0.36.x - Add package auto-discovery

- .github/workflows/run-tests.yml
- resources/views/layouts/scripts.blade.php
- resources/views/layouts/styles.blade.php
- src/Concerns/Internal/AssetManager.php
- src/Facades/Asset.php
- src/Services/AssetService.php
- tests/Unit/AssetFacadeTest.php
- tests/Unit/Views/ScriptsComponentViewTest.php
- tests/Unit/Views/StylesComponentViewTest.php
This release refactors and improves the Asset Service, adding auto-configuration features and a new Asset facade.
Instead of the long syntax `Hyde::assetManager()` you can now use the `Asset` facade directly. See this example, which both do the exact same thing using the same underlying service:
```blade
Hyde::assetManager()->hasMediaFile('app.css')
Asset::hasMediaFile('app.css')
```
If you don't know what any of this means, good news! You don't have to worry about it. Hyde's got your back.
- Added feature to dynamically load hyde.css and hyde.js if they exist locally
- Added the Asset facade to be used instead of `Hyde::assetManager()`
- Added the Asset facade as a class alias to `config/app.css`
- Changed `scripts.blade.php` and `styles.blade.php` to use the Asset facade
- Deprecated …
> v0.41.0-beta - 2022-06-24 - Improve the AssetService

- src/Commands/HydeBuildStaticSiteCommand.php
Fix https://github.com/hydephp/develop/issues/102 Change Prettier integration to only modify HTML files https://github.com/hydephp/develop/commit/b81724f80e6177ed97097d663bca130ab072bee7
In HydeBuildStaticSiteCommand.php
```diff
- 'npx prettier '.Hyde::pathToRelative(Hyde::getSiteOutputPath()).'/ --write --bracket-same-line',
+ 'npx prettier '.Hyde::pathToRelative(Hyde::getSiteOutputPath()).'/**/*.html --write --bracket-same-line',
```
> Fix #102 Add glob pattern to Prettier command

- resources/views/layouts/docs.blade.php
- resources/views/pages/documentation-search.blade.php
- src/Commands/HydeBuildSearchCommand.php
- Added a `@section` hook to the docs layout to allow yielding content
- Change the the Prettier integration to only modify HTML files https://github.com/hydephp/develop/issues/102
- Change how the `docs/search.html` page is rendered, by handling page logic in the view, to decouple it from the build search command
- Fix bug https://github.com/hydephp/develop/issues/93 where styles were missing on search.html when changing the output directory to root
> Improve the full page documentation search

- .github/workflows/run-tests.yml
- codecov.yml
@caendesilva sorry for taking so long, I have an idea on how to get https://github.com/hydephp/framework/commit/94ef84283550d7f92c94fd040c90b349e0dba63a working. I don't actually know how to run the GitHub Actions in this PR, but if possible, I'd like to see if this clears up the issue from https://community.codecov.com/t/codecov-not-discovering-files-when-uploaded-in-ci/3691/2
> feat: add back Codecov with all files

- .github/workflows/run-tests.yml
- tests/Unit/HydeConfigFilesAreMatchingTest.php
Fixes the issue in https://github.com/hydephp/framework/pull/571 which fails due to the workflow checking out the develop branch.
Also cherry picks https://github.com/hydephp/develop/pull/1339: Skip unit test when not running in the monorepo https://github.com/hydephp/develop/commit/48955e572be0e1dcfe279c6e19f23802ce8063f3
> Internal: Update test workflow to dynamically install the proper framework version

- src/Framework/Services/AssetService.php
- tests/Unit/AssetServiceUnitTest.php
Cherry-picks https://github.com/hydephp/develop/pull/1323 to master in preparation for a patch release.
> Fix wrong HydeFront version constant

- .github/workflows/run-tests.yml
- config/docs.php
- config/hyde.php
- resources/views/components/docs/sidebar-footer-text.blade.php
- resources/views/components/docs/sidebar-items.blade.php
- resources/views/components/docs/sidebar.blade.php
- src/Console/Commands/ServeCommand.php
- src/Foundation/HydeKernel.php
- src/Foundation/Internal/LoadConfiguration.php
- src/Foundation/Internal/LoadYamlConfiguration.php
- src/Framework/Factories/NavigationDataFactory.php
- src/Framework/Features/Navigation/DocumentationSidebar.php
- src/Framework/Features/XmlGenerators/SitemapGenerator.php
- tests/Feature/Commands/ServeCommandTest.php
- tests/Feature/LoadYamlConfigurationTest.php
- tests/Feature/Services/DocumentationSidebarTest.php
- tests/Feature/Services/SitemapServiceTest.php
- tests/Feature/SidebarViewTest.php
- tests/Unit/LoadConfigurationTest.php
- tests/Unit/NavigationDataFactoryUnitTest.php
- tests/Unit/ServeCommandOptionsUnitTest.php
Please see the release notes in the development monorepo https://github.com/hydephp/develop/releases/tag/v1.4.0
> HydePHP v1.4.0 - 2023-12-11

- src/Foundation/HydeKernel.php
- src/Foundation/Kernel/Filesystem.php
- src/Foundation/PharSupport.php
- tests/Feature/Foundation/FilesystemTest.php
- tests/Feature/PharSupportTest.php
- Improve support for running HydePHP through the Phar archive https://github.com/hydephp/develop/commit/e361c3e0f78f77c1ea20305dd015b2fcc082c8f8
> HydePHP v1.4.1 - 2023-12-12

- config/hyde.php
- resources/views/layouts/head.blade.php
- resources/views/layouts/scripts.blade.php
- tests/Unit/Views/HeadComponentViewTest.php
- tests/Unit/Views/ScriptsComponentViewTest.php
Merges pull request https://github.com/hydephp/develop/pull/1542
> Add configuration options to add HTML to the head and scripts sections

- resources/views/layouts/head.blade.php
- resources/views/layouts/scripts.blade.php
- tests/Unit/Views/HeadComponentViewTest.php
- tests/Unit/Views/ScriptsComponentViewTest.php
Merges pull request https://github.com/hydephp/develop/pull/1554
> Support using HTML includes to set head and script HTML

- src/Framework/Actions/PostBuildTasks/GenerateRssFeed.php
- src/Framework/Actions/PostBuildTasks/GenerateSitemap.php
Fixes a bug where the sitemap and RSS feed generator commands did not work when the `_site/` directory was not present, and adds some cleanups to the commands.
Merges pull request https://github.com/hydephp/develop/pull/1654
> Fix issues with the sitemap and RSS feed generator commands

- src/Framework/Features/BuildTasks/BuildTask.php
- tests/Unit/BuildTaskUnitTest.php
Merges pull request https://github.com/hydephp/develop/pull/1661
> Fix extra newline being written for failing build tasks

- .github/workflows/run-tests.yml
Improve the test environment setup process by using a local Composer package path instead of trying to require the right branch name though GitHub. This is both less complex, and should make so that the tests can also run in forks. May also be a tiny bit faster due to less network calls.
> Internal: Improve the test environment setup process

- src/Console/Commands/ServeCommand.php
- src/Support/DataCollections.php
- tests/Feature/Commands/BuildRssFeedCommandTest.php
- tests/Feature/Commands/BuildSitemapCommandTest.php
- tests/Feature/ConfigurableFeaturesTest.php
- tests/Feature/Foundation/HyperlinksTest.php
- tests/Feature/GlobalMetadataBagTest.php
- tests/Feature/HydePageTest.php
- tests/Feature/MetadataHelperTest.php
- tests/Feature/MetadataTest.php
- tests/Feature/Services/BuildTaskServiceTest.php
- tests/Feature/Services/RssFeedServiceTest.php
- tests/Feature/Services/SitemapServiceTest.php
- tests/Feature/Services/ValidationServiceTest.php
- tests/Feature/SiteTest.php
- tests/Feature/SitesWithoutBaseUrlAreHandledGracefullyTest.php
- tests/Feature/StaticSiteServiceTest.php
- tests/Feature/Views/MetadataViewTest.php
- tests/Unit/Foundation/HyperlinksUrlPathHelpersTest.php
- tests/Unit/Pages/MarkdownPostHelpersTest.php
- Merges pull request https://github.com/hydephp/develop/pull/1747
- Merges pull request https://github.com/hydephp/develop/pull/1752
> Internal: Extract testing helpers and refactor tests

- src/Foundation/Kernel/Hyperlinks.php
- tests/Feature/HelpersTest.php
- tests/Unit/Foundation/HyperlinksUrlPathHelpersTest.php
Merges pull request https://github.com/hydephp/develop/pull/1757
> Update the Hyde URL helper to not modify already qualified URLs

- src/Framework/Services/AssetService.php
- src/Framework/Services/MarkdownService.php
- tests/Feature/MarkdownServiceTest.php
- tests/Feature/StaticSiteBuilderDocumentationModuleTest.php
- tests/Unit/AssetServiceUnitTest.php
Merges pull request https://github.com/hydephp/develop/pull/1803
> Improve the documentation heading permalinks feature

- src/Support/Filesystem/MediaFile.php
This allows `.webp` images to be automatically supported in builds.
> Add `webp` to the list of default media extensions

- src/Facades/Filesystem.php
- src/Foundation/Kernel/FileCollection.php
- src/Foundation/Kernel/Filesystem.php
- src/Framework/Actions/Internal/FileFinder.php
- src/Framework/Actions/PreBuildTasks/CleanSiteDirectory.php
- src/Support/DataCollections.php
- src/Support/Filesystem/MediaFile.php
- tests/Feature/DiscoveryServiceTest.php
- tests/Feature/FileCollectionTest.php
- tests/Feature/Foundation/FilesystemTest.php
- tests/Unit/DataCollectionUnitTest.php
- tests/Unit/FileFinderTest.php
- tests/Unit/Pages/PageModelGetFileHelpersTest.php
Merges https://github.com/hydephp/develop/pull/2064 into master for a patch release
> Replace `GLOB_BRACE` with a more robust solution

- src/Hyde.php
Merges pull request https://github.com/hydephp/develop/pull/1919
> Update the Hyde facade to use a mixin annotation instead of method annotations

- src/Foundation/Concerns/ForwardsHyperlinks.php
- src/Foundation/Kernel/Hyperlinks.php
Merges pull request https://github.com/hydephp/develop/pull/1993
> Deprecate `Hyde::mediaLink` being replaced by `Hyde::asset()` in v2

- src/Support/Concerns/Serializable.php
- tests/Unit/SerializableTest.php
Merges the following pull requests:
- Update the `Serializable` trait to provide a default automatic `toArray` method in https://github.com/hydephp/develop/pull/1791
- Extract helper method for automatic serialization in https://github.com/hydephp/develop/pull/1793
> Improve the `Serializable` trait to support automatic serialization

- src/Framework/Features/Blogging/Models/PostAuthor.php
- src/Framework/Features/XmlGenerators/RssFeedGenerator.php
- tests/Feature/MarkdownPostTest.php
- tests/Unit/PostAuthorTest.php
Merges pull requests https://github.com/hydephp/develop/pull/1794 and https://github.com/hydephp/develop/pull/1795
> Update the post author class to prepare for the v2 overhaul

- config/docs.php
- src/Foundation/HydeKernel.php
HydePHP v2.0 represents a major evolution of the framework, introducing significant improvements to the asset system, navigation API, and overall developer experience. This release modernizes the frontend tooling by replacing Laravel Mix with Vite, completely rewrites the navigation system for better flexibility, and introduces numerous performance optimizations throughout the framework.
This document will give you an overview of the changes. When you're ready to upgrade your site, take a look at the [Upgrade Guide](https://hydephp.com/docs/2.x/upgrade-guide).
We've replaced Laravel Mix with Vite for a faster, more modern development experience:
- **Instant Hot Module Replacement (HMR)** for real-time updates during development
- **Direct asset compilation** into the `_media` folder for …
> HydePHP v2.0.0 - 2025-10-01

- src/Framework/Services/MarkdownService.php
- tests/Feature/MarkdownServiceTest.php
- https://github.com/hydephp/develop/pull/2332
> [2.x] Improve documentation page detection in MarkdownService 
